---
  - src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse

  - src: https://github.com/rrr89817384657-collab/vector-role.git
    scm: git
    version: "v1.0.0"
    name: vector-role

  - src: htps://github.com/rrr89817384657-collab/lighthouse-role.git
    scm: git
    version: "v1.0.0"
    name: lighthouse-role