- name: Install Clickhouse
  hosts: clickhouse
  tags: clickhouse
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  tags: vector
  roles:
    - vector-role

- name: Install Lighthouse
  hosts: lighthouse
  tags: lighthouse
  roles:
    - lighthouse-role

